### ISSUE TITLE
shinybrowser and rmarkdown::run()

### ISSUE THREAD

**Issue by nplatonov** [daattali/shinybrowser#7]
Is it possible to use **`shinybrowser`** inline in Rmarkdown with `runtme: shiny` option?

    ---
    pagetitle: get_all_info() returns error
    runtime: shiny
    ---
    
    ```{r}
    shinybrowser::detect()
    renderPrint({
       ret <- try(shinybrowser::get_all_info())
       str(ret)
    })
    ```

**Comment by daattali** [comment]
@nplatonov thanks for the report. This was caused by https://github.com/rstudio/htmltools/issues/375

It's now fixed, you should be able to use shinybrowser in Rmarkdown documents without doing anything special if you install the latest github version.

You can also use the previous CRAN version by wrapping the detect() call in any shiny tag. For example `tagList(shinybrowser::detect())`
